yml update

diff --git a/.github/workflows/sync-data.yml b/.github/workflows/sync-data.yml
--- a/.github/workflows/sync-data.yml
+++ b/.github/workflows/sync-data.yml
@@ -1,36 +1,46 @@
-# This is a basic workflow to help you get started with Actions
+name: Sample Site Validation
 
-name: CI
-
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
   pull_request:
-    branches: [ "main" ]
 
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
+permissions:
+  pull-requests: write
+  issues: write
+  repository-projects: write
+  contents: write
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  validate:
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
+    
+    env:
+     Codeql.Enabled: true
+     
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          repository: Sreenivas-Kalluru/Perform-Dynamic-PR.git
+          ref: main # or the branch you want to work   with
+          github-token: "${{ secrets.GITHUB_TOKEN }}"
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+      - name: Sync Meta data Information 
+        run: Scripts/syncMetadata.sh
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Create and Push File
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          git config --local user.email "actions@github.com"
+          git config --local user.name "GitHub Actions"
+          git add  Scripts/commit.txt
+          git commit -m 'Data Updated' ||  echo 'No changes to commit'
+          git fetch origin main
+          git push origin HEAD:main || echo "Error occurred while push to origin"
+
+      - name: Check for differences
+        run: |
+          if ! git diff --quiet; then
+            echo "::error ::Detected changes when regenerating website."
+            git diff --stat
+            exit 1
+          fi
+
